#!/bin/bash
 
jawaban="Y"
 
read -p "Apakah kamu yakin akan menginstall webserver ? (Y/n) " pilih;
 
if [ $pilih == $jawaban ];
then
    echo "Menyiapkan Installasi Web server"
    sudo apt-get update
    echo "Melakukan Installasi Webserver"
    sudo apt-get install -y apache2 php php-mysql
    sudo apt-get install unzip
    echo "Installasi Selesai"
    echo "=============================>"
    echo "Downloading Data"
    echo "=============================>"
    cd
    wget https://codeload.github.com/sdcilsy/landing-page/zip/refs/heads/master
    echo "=============================>"
    echo "Ekstrak File"
    echo "=============================>"
    unzip master
    echo "=============================>"
    echo "Memindahkan data"
    echo "=============================>"
    sudo rm /var/www/html/*
    sudo rm -R /var/www/html/*
    sudo mv landing-page-master/* /var/www/html

    echo "Setup selesai"
    exit 0
else
    echo "Installasi dibatalkan"
    exit 1
fi
